const fs = require('fs');

const path = 'C:/Users/LENOVADEM/Documents/Antigravinity/Creaizen/revenue-recovery/src/lib/db.ts';
let content = fs.readFileSync(path, 'utf8');

const replacements = {
  "E-Posta Gönderildi": "Email Sent",
  "Telefonla Arandı": "Phone Call",
  "Sosyal Ağ / LinkedIn": "Social Network / LinkedIn",
  "TechCorp A.Ş.": "TechCorp Inc.",
  "Ahmet Yılmaz (CEO)": "John Smith (CEO)",
  "E-Ticaret Altyapı Yenilemesi": "E-Commerce Infrastructure Renewal",
  "Fiyat tereddüdü veya karar erteleme sebebiyle teklif sonrası takip unutuldu.": "Follow-up missed after proposal due to price hesitation or decision delay.",
  "Zaman odaklı, hızlı takip. Pürüz giderici ve net.": "Time-sensitive, quick follow-up. Friction-removing and clear.",
  "Ahmet Bey merhaba, E-Ticaret altyapısı projemizle ilgili önceliklerin değişip değişmediğini kontrol etmek istedim. Taslak veya bütçe konusunda aklınıza takılan bir nokta varsa hızlıca netleştirebiliriz.": "Hi John, I wanted to check if priorities have changed regarding our E-Commerce infrastructure project. If you have any questions about the draft or budget, we can quickly clarify them.",
  "10 Nisan 2026": "April 10, 2026",
  "Aday Oluşturuldu": "Lead Created",
  "Web sitesi üzerinden e-ticaret altyapısı için talep oluşturuldu.": "Request for e-commerce infrastructure created via website.",
  "12 Nisan 2026": "April 12, 2026",
  "İlk Temas Kuruldu": "First Contact Established",
  "Ahmet Yılmaz ile gereksinim detayları görüşüldü.": "Requirement details discussed with John Smith.",
  "15 Nisan 2026": "April 15, 2026",
  "Teklif Gönderildi": "Proposal Sent",
  "Yıllık lisans ve altyapı bedelini içeren resmi teklif iletildi.": "Official proposal including annual license and infrastructure fee was sent.",
  "16 Nisan 2026": "April 16, 2026",
  "Teklif İncelendi": "Proposal Viewed",
  "Müşteri adayının teklif dosyasını 3 kez açıp okuduğu tespit edildi.": "It was detected that the prospect opened and read the proposal file 3 times.",
  "30 Nisan 2026": "April 30, 2026",
  "Takip Araması Kaçırıldı": "Follow-up Call Missed",
  "Teklif sonrası yapılması gereken 14. gün takip görüşmesi planlanmadı (Gelir Kaçağı!).": "The 14th day follow-up meeting after the proposal was not planned (Revenue Leak!).",
  "05 Mayıs 2026": "May 05, 2026",
  "Kurtarma Tetiklendi": "Recovery Triggered",
  "Olay güdümlü motor tarafından acil kurtarma süreci başlatıldı.": "Emergency recovery process initiated by event-driven engine.",
  "Lumina Mimarlık": "Lumina Architecture",
  "Selin Kaya (Kurucu)": "Jane Doe (Founder)",
  "Pro Danışmanlık Üyeliği": "Pro Consulting Membership",
  "Sisteme giriş sıklığında %60 düşüş tespit edildi. İptal ve çürüme riski.": "A 60% drop in login frequency detected. Risk of cancellation and decay.",
  "Değer hatırlatıcı, Akıllı Nazik Hatırlatma (Baskısız).": "Value reminder, Smart Gentle Reminder (No Pressure).",
  "Selin Hanım, sistemdeki son raporunuzu incelediğimde 'Aylık Strateji Değerlendirmesi' hakkınızı henüz kullanmadığınızı fark ettim. Bu hafta 15 dakikalık bir kontrol görüşmesi ayarlayalım mı?": "Jane, I noticed when reviewing your last report in the system that you haven't used your 'Monthly Strategy Assessment' right yet. Shall we set up a 15-minute check-in call this week?",
  "01 Ocak 2026": "January 01, 2026",
  "Abonelik Başlatıldı": "Subscription Started",
  "Pro danışmanlık paketi 12 aylık taahhüt ile aktif edildi.": "Pro consulting package activated with 12-month commitment.",
  "15 Mart 2026": "March 15, 2026",
  "Kullanım Zirvesi": "Peak Usage",
  "Müşteri platform panellerini haftada ortalama 4 kez kullandı.": "Customer used platform panels on average 4 times a week.",
  "Aktivite Çürümesi": "Activity Decay",
  "Platform oturumlarında %60 oranında sert bir düşüş tespit edildi.": "A sharp 60% drop in platform sessions detected.",
  "01 Mayıs 2026": "May 01, 2026",
  "Etkileşimsiz Dönem": "Inactive Period",
  "Son 30 gündür hiçbir panel hareketi veya danışmanlık görüşmesi kaydedilmedi.": "No panel movement or consulting meeting recorded in the last 30 days.",
  "12 Mayıs 2026": "May 12, 2026",
  "Çürüme Uyarısı": "Decay Warning",
  "Müşteri geri kazanımı için otomasyon tetiklendi.": "Automation triggered for customer recovery.",
  "Nexus Lojistik": "Nexus Logistics",
  "Caner Öz (Operasyon Müdürü)": "Mike Johnson (Operations Manager)",
  "Geçmiş Alışveriş (2025 Q1)": "Past Purchase (2025 Q1)",
  "Son başarılı projeden bu yana 7 aydır hiçbir iletişim kurulmadı. Churn riski.": "No communication established for 7 months since the last successful project. Churn risk.",
  "İlişki odaklı, satış kokmayan güven tazelemesi.": "Relationship-focused, non-salesy trust renewal.",
  "Caner Bey merhaba, uzun zamandır görüşemedik. Geçen yılki lojistik otomasyonu projenizin nasıl gittiğini merak ettim. Umarım her şey yolundadır, kahve içmeye bekleriz.": "Hi Mike, long time no see. I wondered how your logistics automation project from last year was going. Hope everything is alright, let's grab coffee sometime.",
  "15 Eylül 2025": "September 15, 2025",
  "İlk Sözleşme": "First Contract",
  "Lojistik otomasyon projesi için el sıkışıldı.": "Shook hands for the logistics automation project.",
  "20 Ekim 2025": "October 20, 2025",
  "Proje Başarıyla Kapatıldı": "Project Closed Successfully",
  "Kurulumlar tamamlandı ve ciro tahsil edilerek proje kapatıldı.": "Installations completed and project closed after revenue collected.",
  "01 Kasım 2025": "November 01, 2025",
  "Destek Talebi": "Support Request",
  "Ufak bir optimizasyon talebi çözülerek teslim edildi.": "A minor optimization request was solved and delivered.",
  "15 Kasım 2025": "November 15, 2025",
  "İletişim Donması": "Communication Freeze",
  "Son işlemden bu yana firma ile hiçbir kanaldan diyalog kurulmadı.": "No dialogue established with the company through any channel since the last transaction.",
  "15 Mayıs 2026": "May 15, 2026",
  "Soğuk Hat Hatırlatması": "Cold Line Reminder",
  "İletişim boşluğunu kapatmak adına ilişki tazeleyici aksiyon tetiklendi.": "Relationship refreshing action triggered to close the communication gap.",
  "tr-TR": "en-US",
  "Son başarılı projeden bu yana uzun süredir hiçbir diyalog kurulmadı. Unutulma ve rakibe kayma riski.": "No dialogue established for a long time since the last successful project. Risk of being forgotten and shifting to competitor.",
  "İlişki odaklı, satış kokmayan samimi güven tazelemesi.": "Relationship-focused, non-salesy sincere trust renewal.",
  "uzun zamandır görüşemedik.": "long time no see.",
  "Son projenizin": "Your last project's",
  "nasıl gittiğini merak ettim. Umarım her şey harika gidiyordur, kahve içmeye bekleriz.": "how it went. Hope everything is going great, let's grab coffee.",
  "10 Ay Önce": "10 Months Ago",
  "İlk Müşteri Tanımı": "First Customer Definition",
  "Müşteri kaydı veritabanında oluşturuldu.": "Customer record created in the database.",
  "8 Ay Önce": "8 Months Ago",
  "Fırsat Kazanıldı": "Opportunity Won",
  "İlgili proje bütçesiyle başarıyla tamamlandı.": "Related project successfully completed with its budget.",
  "6 Ay Önce": "6 Months Ago",
  "İletişim Boşluğu": "Communication Gap",
  "Destek veya satış kanallarında 6 aydır sıfır hareket.": "Zero movement in support or sales channels for 6 months.",
  "Bugün": "Today",
  "Teşhis Tetiklendi": "Diagnosis Triggered",
  "Sessiz müşteri kaybını önlemek üzere kurtarma radarına alındı.": "Taken into recovery radar to prevent silent customer loss.",
  "Yüksek cirolu teklif sunulmuş ancak takip aranması kaçırıldığı için beklemede kalmış.": "High-revenue proposal presented but left pending because follow-up call was missed.",
  "Zaman duyarlı takip araması. Karar engelini çözücü net teklif.": "Time-sensitive follow-up call. Clear proposal to resolve decision obstacle.",
  "projemizle ilgili önceliklerin değişip değişmediğini kontrol etmek istedim. Teklif veya bütçe detaylarında aklınıza takılan bir nokta varsa hızlıca netleştirebiliriz.": "I wanted to check if priorities have changed regarding our project. If you have any questions about proposal or budget details, we can quickly clarify them.",
  "25 Gün Önce": "25 Days Ago",
  "Talep Alındı": "Request Received",
  "Web formundan teklif talebi kaydedildi.": "Proposal request from web form recorded.",
  "20 Gün Önce": "20 Days Ago",
  "Aday Nitelendirildi": "Lead Qualified",
  "Gereksinim analizi tamamlanarak bütçe onaylandı.": "Requirement analysis completed and budget approved.",
  "15 Gün Önce": "15 Days Ago",
  "Teklif İletildi": "Proposal Forwarded",
  "Resmi teklif dokümanı paylaşıldı.": "Official proposal document shared.",
  "12 Gün Önce": "12 Days Ago",
  "Müşteri İnceledi": "Customer Reviewed",
  "Müşteri teklif dosyasını görüntüledi ancak yanıt dönmedi.": "Customer viewed the proposal file but didn't respond.",
  "5 Gün Önce": "5 Days Ago",
  "Takip Araması Unutuldu": "Follow-up Call Forgotten",
  "Teklif takip araması takvimde gecikti (Gelir Kaçağı!).": "Proposal follow-up call delayed in calendar (Revenue Leak!).",
  "Takip Kurtarma Tetiklendi": "Follow-up Recovery Triggered",
  "Kurtarma motoru acil AI takibi önerdi.": "Recovery engine suggested urgent AI follow-up.",
  "Son 30 günde platform kullanım sıklığında veya abonelik etkileşiminde çürüme saptandı.": "Decay detected in platform usage frequency or subscription engagement in the last 30 days.",
  "Fayda hatırlatıcı nazik temas. Ekstra destek teklifi.": "Benefit-reminding gentle contact. Extra support offer.",
  "sistem verilerinizi incelediğimizde bazı üyelik avantajlarınızı henüz kullanmadığınızı fark ettik. Bu hafta kısa bir görüşme ayarlayalım mı?": "we noticed when reviewing your system data that you haven't used some of your membership benefits yet. Shall we set up a short meeting this week?",
  "60 Gün Önce": "60 Days Ago",
  "Hizmet Başladı": "Service Started",
  "Abonelik paketi sorunsuz aktif edildi.": "Subscription package activated without issues.",
  "45 Gün Önce": "45 Days Ago",
  "Etkin Kullanım": "Active Usage",
  "Müşteri platformda ilk projelerini oluşturdu.": "Customer created their first projects on the platform.",
  "30 Gün Önce": "30 Days Ago",
  "Etkileşim Kaybı": "Engagement Loss",
  "Sisteme giriş sıklığı %40 oranında azaldı.": "System login frequency decreased by 40%.",
  "İptal Önleme Tetiklendi": "Cancellation Prevention Triggered",
  "Çürüme eylemini durdurmak için geri kazanım aksiyonu başlatıldı.": "Recovery action started to stop the decay process.",
  "Bilinmeyen Firma": "Unknown Company",
  "Bilinmiyor": "Unknown",
  "Genel Değerlendirme": "General Assessment",
  "Kurtarma Başlatıldı": "Recovery Started",
  "AI Mesaj Şablonu": "AI Message Template",
  "kanalı ile gönderildi.": "sent via channel.",
  "Döngü Kapatıldı": "Loop Closed",
  "Sonuçlandırıldı": "Concluded",
  "Gelir Kurtarıldı!": "Revenue Recovered!",
  "Kurtarıldı (Gelir Geri Kazanıldı)": "Recovered (Revenue Gained Back)",
  "Yanıt Alındı": "Replied",
  "Yanıt Alındı (İletişim Aktif)": "Replied (Active Communication)",
  "Fırsat Yeniden Açıldı": "Opportunity Reopened",
  "Yeniden Açıldı (Süreç Baştan Başladı)": "Reopened (Process Restarted)",
  "Yanıt Yok": "No Response",
  "Cevap Alınamadı": "No Answer Received",
  "Kayıp (Churn)": "Lost (Churn)",
  "Müşteri Kaybedildi / Churn": "Customer Lost / Churn",
  "Döngü Sonlandırıldı. Sonuç:": "Loop Concluded. Result:"
};

for (const [key, value] of Object.entries(replacements)) {
  content = content.replace(new RegExp(key.replace(/[.*+?^${}()|[\]\\]/g, '\\$&'), 'g'), value);
}

fs.writeFileSync(path, content, 'utf8');
console.log("Translated db.ts");
