const fs = require('fs');

function replaceInFile(filePath, replacements) {
  let content = fs.readFileSync(filePath, 'utf8');
  for (const [key, value] of Object.entries(replacements)) {
    content = content.replace(new RegExp(key.replace(/[.*+?^${}()|[\]\\]/g, '\\$&'), 'g'), value);
  }
  fs.writeFileSync(filePath, content, 'utf8');
  console.log("Translated", filePath);
}

const basePath = 'C:/Users/LENOVADEM/Documents/Antigravinity/Creaizen/revenue-recovery/src/components/';

// FeedbackModal.tsx
replaceInFile(basePath + 'FeedbackModal.tsx', {
  "Lütfen tüm zorunlu alanları yanıtlayın.": "Please answer all mandatory fields.",
  "Çok Faydalı": "Very Useful",
  "Biraz Faydalı": "Somewhat Useful",
  "Faydalı Değil": "Not Useful",
  "Kayıp Müşteriler": "Lost Customers",
  "Abonelik Çürümesi": "Subscription Decay",
  "Terk Edilmiş Fırsatlar": "Abandoned Opportunities",
  "Gelir Tahmini": "Revenue Estimate",
  "Geri Bildirim & Hata Raporu": "Feedback & Bug Report",
  "Değerli Katkınız İçin Teşekkürler!": "Thank You For Your Valuable Contribution!",
  "Geri bildiriminiz başarıyla kaydedildi. Görüş ve hata raporlarınız admin kontrol paneline iletilmiştir.": "Your feedback has been successfully recorded. Your comments and bug reports have been forwarded to the admin dashboard.",
  "Kapat": "Close",
  "Deneyiminizi mükemmelleştirmek istiyoruz. Lütfen geri bildiriminizi veya karşılaştığınız hataları bizimle paylaşın.": "We want to perfect your experience. Please share your feedback or any bugs you encountered with us.",
  "Geri Bildirim Türü": "Feedback Type",
  "🪲 Hata Raporu": "🪲 Bug Report",
  "💡 Öneri/Fikir": "💡 Suggestion/Idea",
  "❓ Soru/Yardım": "❓ Question/Help",
  "1. RRIO Teşhis Raporu işletmeniz için ne kadar faydalı oldu? *": "1. How useful was the RRIO Diagnostic Report for your business? *",
  "2. Sizce platformdaki en değerli özellik hangisiydi? *": "2. What do you think was the most valuable feature on the platform? *",
  "Kayıp Müşteri Analizi": "Lost Customer Analysis",
  "Askıda Kalan Fırsatlar": "Pending Opportunities",
  "Ciro & Kaçak Tahmini": "Revenue & Leakage Estimate",
  "Hata Detayları / Öneriler / Görüşler": "Bug Details / Suggestions / Feedback",
  "Karşılaştığınız bir hata varsa adımlarını yazabilir veya geliştirmemizi istediğiniz özellikleri belirtebilirsiniz...": "If you encountered a bug, you can write the steps or specify the features you want us to improve...",
  "Gönder 🚀": "Submit 🚀"
});

// GoogleOAuthModal.tsx
replaceInFile(basePath + 'GoogleOAuthModal.tsx', {
  "Google Workspace Entegrasyonu": "Google Workspace Integration",
  "Bu bir <strong>demo simülasyonudur</strong>. Gerçek Google hesabınıza bağlanılmaz,\n            hiçbir veri okunmaz veya saklanmaz.": "This is a <strong>demo simulation</strong>. It does not connect to your real Google account,\n            no data is read or stored.",
  "E-Posta Arşivini Tara": "Scan Email Archive",
  "Gmail &amp; Takvim akışlarınız analiz edilerek sessiz kalmış fırsatlar,\n            unutulmuş teklifler ve soğuyan ilişkiler tespit edilecektir.\n            Yalnızca metadata ve iletişim frekansı okunur.": "Your Gmail & Calendar streams will be analyzed to detect silent opportunities,\n            forgotten proposals, and cooling relationships.\n            Only metadata and communication frequency are read.",
  "Güvenli Bağlantı Kuruluyor...": "Establishing Secure Connection...",
  "Google ile Devam Et": "Continue with Google",
  "Global Güvenlik Standartları": "Global Security Standards",
  "RRIO verilerinizi ASLA kendi sunucularında saklamaz veya üçüncü partilerle paylaşmaz.": "RRIO NEVER stores your data on its servers or shares it with third parties.",
  "Sadece \"Read-Only\" (Salt Okunur) analiz izni istenir. E-postalarınız değiştirilemez.": "Only \"Read-Only\" analysis permission is requested. Your emails cannot be modified.",
  "Tamamen GDPR ve KVKK uyumlu uçtan uca şifreleme mimarisi (AES-256).": "Fully GDPR compliant end-to-end encryption architecture (AES-256)."
});

// PricingModal.tsx
replaceInFile(basePath + 'PricingModal.tsx', {
  "Güvenli Ödeme Ödemesi": "Secure Checkout Payment",
  "SaaS Planınızı Yükseltin": "Upgrade Your SaaS Plan",
  "İşletmenizin gelir kaçaklarını anında durdurun.": "Stop your business's revenue leaks instantly.",
  "Bu ödeme ekranı bir simülasyondur. Gerçek ücret alınmaz. Deneyim amaçlıdır.": "This checkout screen is a simulation. No real charge will be made. For experience purposes only.",
  "Aylık Ödeme": "Monthly Billing",
  "Yıllık Ödeme": "Annual Billing",
  "%20 TASARRUF": "SAVE 20%",
  "Sınırlı kısıtlı teşhis moduyla platformu tanıma.": "Get to know the platform with limited restricted diagnostic mode.",
  " / sonsuza kadar": " / forever",
  "İlk 15 CSV Satır Analizi": "First 15 CSV Rows Analysis",
  "Temel Sızıntı Teşhisi": "Basic Leakage Diagnosis",
  "Max 3 AI Taslak Hazırlama": "Max 3 AI Draft Preparation",
  "🔒 Gelişmiş Pipeline (Kilitli)": "🔒 Advanced Pipeline (Locked)",
  "🔒 Kapsamlı Sonuç Takibi (Kilitli)": "🔒 Comprehensive Outcome Tracking (Locked)",
  "Mevcut Plan": "Current Plan",
  "Küçük ve orta ölçekli B2B ekipleri için tam kurtarma aracı.": "Full recovery tool for small and medium B2B teams.",
  " / ay": " / mo",
  "(yıllık faturalandırılır)": "(billed annually)",
  "Max 500 Satır CSV Yükleme": "Max 500 Rows CSV Upload",
  "Limitsiz AI Geri Kazanım Şablonları": "Unlimited AI Recovery Templates",
  "Kapsamlı Sonuç & Pipeline Yönetimi": "Comprehensive Outcome & Pipeline Management",
  "Yönetici PDF Raporları İndirme": "Executive PDF Reports Download",
  "Hata & Geri Bildirim Önceliği": "Bug & Feedback Priority",
  "Pro'ya Geç": "Upgrade to Pro",
  "EN YÜKSEK KAZANÇ": "HIGHEST ROI",
  "Ajanslar ve çoklu hesap yöneten profesyoneller için.": "For agencies and professionals managing multiple accounts.",
  "Pro Plandaki Her Şey": "Everything in Pro Plan",
  "Sınırsız/Limitsiz Satır Analizi": "Unlimited Row Analysis",
  "Beyaz Etiketli (White-label) PDF Çıktısı": "White-label PDF Output",
  "Çoklu Firma/Müşteri Yönetimi": "Multi-Company/Client Management",
  "Webhook Simülasyonu & CRM Otomasyonu": "Webhook Simulation & CRM Automation",
  "Agency'ye Geç": "Upgrade to Agency",
  "Ödeme Başarıyla Tamamlandı!": "Payment Successfully Completed!",
  "SaaS Lisansınız anında oluşturuldu.": "Your SaaS License was created instantly.",
  "Planı": "Plan",
  "özelliklerinin kilitleri açıldı!": "features have been unlocked!",
  "Sayfa yenileniyor ve kilitler kalkıyor...": "Page is refreshing and locks are being removed...",
  "Seçilen Plan": "Selected Plan",
  "💎 Pro Sürüm": "💎 Pro Version",
  "🚀 Agency Sürüm": "🚀 Agency Version",
  "Kart Sahibi Adı Soyadı": "Cardholder Full Name",
  "Kart Numarası": "Card Number",
  "Son Kullanma (AA/YY)": "Expiration (MM/YY)",
  "Güvenlik Kodu (CVC)": "Security Code (CVC)",
  "SSL 256-bit Güvenli Stripe Sandbox Bağlantısı": "SSL 256-bit Secure Stripe Sandbox Connection",
  "⚡ Demo Kart Bilgilerini Otomatik Doldur": "⚡ Auto-fill Demo Card Details",
  "Geri": "Back",
  "Doğrulanıyor...": "Verifying...",
  "Güvenli Ödeme Yap": "Make Secure Payment"
});

// SettingsModal.tsx
replaceInFile(basePath + 'SettingsModal.tsx', {
  "Genel Ayarlar": "General Settings",
  "Abonelik": "Subscription",
  "İptal & İade": "Cancel & Refund",
  "Genel Sistem Ayarları": "General System Settings",
  "Platform genelindeki varsayılan değerleri ve AI stüdyo tonunu özelleştirin.": "Customize platform-wide defaults and AI studio tone.",
  "Firma Adınız": "Company Name",
  "Varsayılan İletişim Tonu": "Default Communication Tone",
  "Kurumsal &amp; Ciddi (Varsayılan)": "Corporate & Serious (Default)",
  "Samimi &amp; Yakın": "Friendly & Warm",
  "Para Birimi": "Currency",
  "Dolar ($)": "Dollar ($)",
  "Euro (€)": "Euro (€)",
  "Türk Lirası (₺)": "Turkish Lira (₺)",
  "Çalışma Prensibi": "Working Principle",
  "Kurtarma Uyarıları": "Recovery Alerts",
  "Kritik sızıntı tespitlerinde bildirim al": "Get notified on critical leakage detections",
  "Kapat": "Close",
  "✓ Kaydedildi!": "✓ Saved!",
  "Değişiklikleri Kaydet": "Save Changes",
  "Abonelik ve Limit Bilgisi": "Subscription and Limit Info",
  "Aktif paketinizi görüntüleyin ve diğer planları inceleyin.": "View your active package and explore other plans.",
  "Aktif": "Active",
  "Mevcut Plan": "Current Plan",
  "Pro Plan": "Pro Plan",
  "$97/Ay · Sınırsız analiz": "$97/Mo · Unlimited analysis",
  "Agency Plan": "Agency Plan",
  "$197/Ay · Çoklu hesap": "$197/Mo · Multiple accounts",
  "Ücretsiz Plan": "Free Plan",
  "Sınırlı analiz kapasitesi": "Limited analysis capacity",
  "Sınırsız Şirket, AI Yanıt Stüdyosu, PDF Raporlama": "Unlimited Companies, AI Reply Studio, PDF Reporting",
  "$97 / Ay": "$97 / Mo",
  "Özel Veritabanı, Entegrasyon API, Dedicated VPS": "Private Database, Integration API, Dedicated VPS",
  "$197 / Ay": "$197 / Mo",
  "Enterprise VPS": "Enterprise VPS",
  "Özel Sunucu, Sınırsız Entegrasyon, 7/24 Destek": "Dedicated Server, Unlimited Integrations, 24/7 Support",
  "İletişime Geçin": "Contact Us",
  "(Demo ortamında ödeme aktif değildir)": "(Payment is not active in Demo environment)",
  "Tüm Paketler": "All Packages",
  "Aboneliği İptal Et &amp; İade İste": "Cancel Subscription & Request Refund",
  "Ayrıldığınızı görmek bizi üzer. Hizmetimizi geliştirebilmemiz için lütfen ayrılma nedeninizi paylaşın.": "We are sad to see you go. Please share your reason for leaving so we can improve our service.",
  "Fiyat çok yüksek": "Price is too high",
  "İstediğim sonucu alamadım": "Didn't get the desired result",
  "Sistemi karmaşık buldum": "Found the system complicated",
  "Sadece denemek istemiştim": "Just wanted to try it out",
  "Vazgeç": "Cancel",
  "Devam Et": "Continue",
  "Belki fikrinizi değiştirirsiniz?": "Maybe you'll change your mind?",
  "Aboneliğinizi iptal etmek yerine size özel bir teklif var.": "Instead of canceling your subscription, we have a special offer for you.",
  "2 Ay Ücretsiz Pro Üyelik": "2 Months Free Pro Membership",
  "İptal işlemini durdurun ve sistemi 2 ay daha ücretsiz kullanın. Herhangi bir kart ücreti çekilmeyecektir.": "Stop the cancellation process and use the system for another 2 months for free. No card fee will be charged.",
  "Teklifi Kabul Et ve Devam Et": "Accept Offer and Continue",
  "Hayır, iptal ve iade işlemine devam et": "No, continue with cancellation and refund",
  "İptal ve İade Talebi Alındı": "Cancellation and Refund Request Received",
  "İade talebiniz işleme alınmıştır. Bankanızın süreçlerine bağlı olarak ücret iadesi 3-5 iş günü içerisinde kartınıza yansıyacaktır.": "Your refund request has been processed. Depending on your bank's processes, the refund will be reflected on your card within 3-5 business days.",
  "Panoya Dön": "Return to Dashboard",
  "Hesap &amp; Ayarlar": "Account & Settings",
  "Sistem tercihlerinizi yönetin": "Manage your system preferences"
});
