const fs = require('fs');
const path = 'C:/Users/LENOVADEM/Documents/Antigravinity/Creaizen/revenue-recovery/src/views/UploadView.tsx';
let content = fs.readFileSync(path, 'utf8');

const replacements = {
  "CSV yüklenirken bir hata oluştu.": "An error occurred while loading CSV.",
  "TrendModa Giyim Ltd.": "TrendFashion Apparel Ltd.",
  "Meltem Öz (E-Ticaret Md.)": "Melissa White (E-Comm Mgr)",
  "Kayıp Sepet & Ödeme Sayfası Kurtarma": "Abandoned Cart & Checkout Recovery",
  "Züccaciye Dünyası": "HomeGoods World",
  "Kaan Demir (Kurucu)": "Kevin Drake (Founder)",
  "Toptan Sipariş Formu Terki": "Wholesale Order Form Abandonment",
  "Kozmetik Deposu": "Cosmetics Depot",
  "Seda Kaya (CFO)": "Sarah King (CFO)",
  "Yıllık B2B Tedarik Sözleşmesi": "Annual B2B Supply Contract",
  "PetShop Pazarı": "PetShop Market",
  "Ali Can (Operasyon)": "Alex Cole (Operations)",
  "Aylık Tekrarlayan Mama Paketi İptali": "Monthly Recurring Food Plan Cancel",
  "Gurme Lezzetler": "Gourmet Delights",
  "Zeynep Tekin (Satış)": "Zoe Taylor (Sales)",
  "Kurumsal Hediye Siparişi Takibi": "Corporate Gift Order Follow-up",
  "Ömer Çelik (Genel Müdür)": "Omar Steel (General Manager)",
  "Akıllı Ev Paketleri Satış Teklifi": "Smart Home Packages Sales Offer",
  "ModaLine Tasarım": "ModaLine Design",
  "Deniz Aslan (Tasarım Direktörü)": "Dennis Lion (Design Director)",
  "VIP Kumaş Alımı Fiyat Teklifi": "VIP Fabric Purchase Price Offer",
  "Selim Yıldız (Kategori Md.)": "Sam Star (Category Mgr)",
  "Toplu Monitör Siparişi Askıda": "Bulk Monitor Order Pending",
  "Alfa Yazılım & Danışmanlık": "Alpha Software & Consulting",
  "Ahmet Yılmaz (CEO)": "Adam Yilmaz (CEO)",
  "Dijital Pazarlama Aylık Retainer": "Digital Marketing Monthly Retainer",
  "Selin Arslan (Kurucu Ortak)": "Selena Arslan (Co-Founder)",
  "Web Arayüz Tasarımı & UX Projesi": "Web UI Design & UX Project",
  "Vega Medya Grubu": "Vega Media Group",
  "Burak Şahin (Direktör)": "Brian Hawk (Director)",
  "Sosyal Medya Yönetim Sözleşmesi": "Social Media Management Contract",
  "Canan Aksoy (SEO Lideri)": "Chloe Aksoy (SEO Lead)",
  "SEO & İçerik Pazarlaması Yenileme": "SEO & Content Marketing Renewal",
  "Delta Video Prodüksiyon": "Delta Video Production",
  "Murat Yıldırım (Yapımcı)": "Mark Lightning (Producer)",
  "Kurumsal Reklam Tanıtım Filmi": "Corporate Commercial Promo Video",
  "Sigma Medya Planlama": "Sigma Media Planning",
  "Eda Kaya (Bütçe Md.)": "Eda Rock (Budget Mgr)",
  "Yıllık Google Ads Yönetim Sözleşmesi": "Annual Google Ads Mgmt Contract",
  "Omni Marka İletişimi": "Omni Brand Communications",
  "Turgut Efe (Kreatif Direktör)": "Tyler Efe (Creative Director)",
  "Rebranding & Logo Çalışması Teklifi": "Rebranding & Logo Design Offer",
  "SaaSify Bulut Sistemleri": "SaaSify Cloud Systems",
  "Bülent Avcı (CTO)": "Ben Hunter (CTO)",
  "Enterprise Bulut Planı (10 Koltuk)": "Enterprise Cloud Plan (10 Seats)",
  "FitLife Spor Merkezleri": "FitLife Sports Centers",
  "Ceren Çetin (Operasyon Direktörü)": "Cersei Cetin (Operations Director)",
  "Yıllık Kurumsal Premium Üyelik": "Annual Corporate Premium Membership",
  "Mert Güler (Eğitim Md.)": "Matt Guler (Education Mgr)",
  "Kurumsal İngilizce Paketi Lisansı": "Corporate English Package License",
  "Sibel Yıldız (Müşteri Yöneticisi)": "Sibel Star (Account Manager)",
  "Ortak Ofis Kullanım Aboneliği": "Co-Working Space Subscription",
  "ChefBox Yemek Servisi": "ChefBox Food Service",
  "Deniz Kaya (Pazarlama)": "Dennis Rock (Marketing)",
  "Kurumsal Günlük Öğle Yemeği Paketi": "Corporate Daily Lunch Package",
  "Hakan Şen (Art Director)": "Hank Sen (Art Director)",
  "Pro Tasarım Şablonları Lisansı": "Pro Design Templates License",
  "Apex Teknoloji A.Ş.": "Apex Technology Inc.",
  "Mert Aksoy (CEO)": "Matt Aksoy (CEO)",
  "Yapay Zeka Danışmanlığı": "Artificial Intelligence Consulting",
  "Nova Retail A.Ş.": "Nova Retail Inc.",
  "Ebru Şahin (CFO)": "Ebru Hawk (CFO)",
  "CRM Lisansı Yenileme": "CRM License Renewal",
  "Atlas Bilişim": "Atlas IT",
  "Burak Yalçın (CTO)": "Brian Yalcin (CTO)",
  "Yıllık Bakım Anlaşması": "Annual Maintenance Agreement",
  "Karya Teknoloji": "Karya Technology",
  "Deniz Eren (Kurucu)": "Dennis Eren (Founder)",
  "Mobil Uygulama Arayüzyüzü": "Mobile App UI",
  "Vortex Global": "Vortex Global",
  "Hakan Çelik (Direktör)": "Hank Steel (Director)",
  "Bulut Altyapı Desteği": "Cloud Infrastructure Support",
  "rrio_musteri_sablonu.csv": "rrio_customer_template.csv",
  "🛠️ Yönetici Paneli": "🛠️ Admin Panel",
  "Çıkış": "Logout",
  "Gelir Kaçağı İşletim Sistemi": "Revenue Leakage Operating System",
  "Gelirinizin Nereye Sızdığını": "Stop Quietly Watching",
  "Sessizce İzlemeyi Bırakın": "Your Revenue Leak Away",
  "RRIO, e-posta ve CRM verilerinizdeki unutulmuş takipleri, askıda kalmış teklifleri ve \n            çürüyen abonelikleri saniyeler içinde analiz eder. Kaçak cirolarınızı listeler ve kurtarır.": "RRIO analyzes forgotten follow-ups, pending proposals, and decaying subscriptions in your email and CRM data in seconds. It lists and recovers your leaked revenues.",
  "Hemen Teşhis Et": "Diagnose Now",
  "🚀 Hazır Demo Verisiyle Dene": "🚀 Try with Demo Data",
  "1. Veri Entegrasyonu": "1. Data Integration",
  "Geçmiş e-posta veya CRM verilerinizi saniyeler içinde analiz motoruna bağlayın.": "Connect your past email or CRM data to the analysis engine in seconds.",
  "2. Gelir Kaçağı Teşhisi": "2. Revenue Leakage Diagnosis",
  "Unutulmuş takipleri, askıda kalmış teklifleri ve soğuyan müşterileri bulur.": "Finds forgotten follow-ups, pending proposals, and cooling clients.",
  "3. Olay Güdümlü Kurtarma": "3. Event-Driven Recovery",
  "Her kaçağa özel kurtarma şablonları oluşturur ve kurtarma döngüsünü başlatır.": "Creates custom recovery templates for each leak and starts the recovery loop.",
  "Hızlı Hesaplayıcı": "Quick Calculator",
  "Olası Gelir Sızıntınızı Hesaplayın": "Calculate Your Potential Revenue Leakage",
  "Aylık Ortalama Cironuz": "Average Monthly Revenue",
  "Aylık Kayıp Fırsatlar": "Monthly Lost Opportunities",
  "Teklif": "Deals",
  "Hesaplanan Aylık Kaçak Gelir": "Calculated Monthly Leaked Revenue",
  "Fırsat ortalama değeri:": "Average deal value:",
  "RRS İle Geri Kazanılabilir": "Recoverable with RRS",
  "/ Ay": "/ Month",
  "Ortalama %45 geri kazanım başarı oranı": "Average 45% recovery success rate",
  "Kaçakları Tespit Et": "Detect Leakages",
  "Zeka Teşhis Motorunu Başlatın": "Start Intelligence Diagnostic Engine",
  "Verileriniz tamamen yerel tarayıcınızda işlenir. Sunucularımıza hiçbir hassas ciro\n              veya e-posta verisi yüklenmez.": "Your data is processed entirely in your local browser. No sensitive revenue or email data is uploaded to our servers.",
  "%100 Gizlilik Güvencesi.": "100% Privacy Guarantee.",
  "Veri Kaynağı Seçin": "Select Data Source",
  "Google Workspace Tarama": "Google Workspace Scan",
  "Gmail &amp; Takvim veri akışlarını simüle edin": "Simulate Gmail & Calendar data streams",
  "Müşteri / CRM Verisi Yükle": "Upload Customer / CRM Data",
  "CSV dosyanızı yerel analiz motoruna aktarın": "Transfer your CSV file to the local analysis engine",
  "VEYA": "OR",
  "Hazır Demo Veri Setleriyle Deneyin": "Try with Ready Demo Datasets",
  "E-Ticaret Seti": "E-Commerce Set",
  "8 Kaçak Fırsat Analizi": "8 Leaked Opportunity Analysis",
  "Ajans Seti": "Agency Set",
  "7 Müşteri &amp; Teklif Analizi": "7 Customer & Proposal Analysis",
  "Abonelik / Üyelik Seti": "Subscription / Membership Set",
  "6 Abonelik Çürüme Analizi": "6 Subscription Decay Analysis",
  "CSV kolonları hakkında bilgi almak için:": "For information about CSV columns:",
  "Örnek CSV Şablonu İndir": "Download Sample CSV Template",
  "🛡️ %100 KVKK &amp; GDPR Uyumlu Local Sandbox": "🛡️ 100% GDPR Compliant Local Sandbox"
};

for (const [key, value] of Object.entries(replacements)) {
  content = content.replace(new RegExp(key.replace(/[.*+?^${}()|[\]\\]/g, '\\$&'), 'g'), value);
}

fs.writeFileSync(path, content, 'utf8');
console.log("Translation done for UploadView");
