const fs = require('fs');
const path = 'C:/Users/LENOVADEM/Documents/Antigravinity/Creaizen/revenue-recovery/src/views/DiagnosisView.tsx';
let content = fs.readFileSync(path, 'utf8');

const replacements = {
  "Telefonla Arandı": "Phone Call",
  "Sosyal Ağ / LinkedIn": "Social / LinkedIn",
  "Ahmet Bey merhaba": "Hi John",
  "Ahmet Bey selamlar": "Hey John",
  "Selin Hanım": "Jane",
  "Selin selam": "Hey Jane",
  "kontrol etmek istedim": "just checking in",
  "bir yazayım istedim": "wanted to drop a quick line",
  "bekleriz": "hope to hear from you",
  "bekliyorum, sevgiler": "looking forward, cheers",
  "E-Posta Gönderildi": "Email Sent",
  "WhatsApp / SMS": "WhatsApp / SMS",
  "Kurtarıldı": "Recovered",
  "Yanıt Alındı": "Replied",
  "Yeniden Açıldı": "Reopened",
  "Cevap Yok": "No Response",
  "Kayıp / Churn": "Churned",
  "Terk Edilmiş Fırsat": "Abandoned Opportunity",
  "Abonelik Çürümesi": "Subscription Decay",
  "Soğuk İlişki": "Cold Relationship",
  "Kritik": "Critical",
  "Orta": "Medium",
  "Düşük": "Low",
  "Bekliyor": "Pending",
  "İletişimde": "Action Taken",
  "Sonuçlandı": "Concluded",
  "Yönetici Raporu": "Executive Report",
  "Toplam Sızıntı Tutarı": "Total Leakage Amount",
  "Toplam Sızıntı": "Total Leakage",
  "Kurtarılabilir": "Recoverable",
  "Kurtarılan Ciro": "Recovered Revenue",
  "Tespit Edilen Riskler": "Detected Risks",
  "Müşteri / Proje": "Client / Project",
  "Kategori": "Category",
  "Aciliyet": "Urgency",
  "Risk": "Risk",
  "Durum": "Status",
  "Lütfen geçerli bir e-posta girin.": "Please enter a valid email.",
  "Abonelik Riski:": "Subscription Risk:",
  "Sisteme giriş sıklığında düşüş saptandı. Değer hatırlatıcı temas öneriliyor.": "Drop in login frequency detected. Value reminder contact is suggested.",
  "Kaçırılan Teklif:": "Missed Proposal:",
  "Müşteri teklifi açtı ancak 14 gündür takip yapılmadı. Hızlı aksiyon öneriliyor.": "Client opened the proposal but no follow-up for 14 days. Quick action is suggested.",
  "Teşhis verileri analiz ediliyor...": "Analyzing diagnostic data...",
  "Raporunuzu İndirin": "Download Your Report",
  "Toplam": "Total",
  "kritik sızıntı": "critical leakages",
  "geri kazanılabilir ciro tespit edildi. PDF raporu için e-posta adresinizi girin.": "recoverable revenue detected. Enter your email for the PDF report.",
  "E-Posta Adresiniz": "Your Email Address",
  "İptal": "Cancel",
  "Raporu İndir": "Download Report",
  "Sınırsız Analiz İçin Yükselt": "Upgrade for Unlimited Analysis",
  "Yeniden Tara": "Rescan",
  "Demo'yu Sıfırla": "Reset Demo",
  "Tüm demo verisini sil ve sıfırla": "Delete all demo data and reset",
  "Ayarlar": "Settings",
  "Gelir Rehabilitasyon Operasyonu": "Revenue Rehabilitation Operation",
  "Müşteri veritabanınızdaki sessiz gelir kayıpları ve kurtarma radarı.": "Silent revenue leakage and recovery radar for your customer database.",
  "Sadece İlk 15 Kayıt Analiz Edildi": "Only First 15 Records Analyzed",
  "Ücretsiz planda olduğunuz için dosyanızın sadece ilk 15 satırı işlendi. Kalan kayıtlardaki riskleri görmek ve kurtarma operasyonunu yönetmek için planınızı yükseltin.": "Since you are on the free plan, only the first 15 rows of your file were processed. Upgrade your plan to see risks in the remaining records and manage the recovery operation.",
  "Pro Plana Geç": "Upgrade to Pro",
  "ay)": "mo)",
  "Zeka Teşhis Raporu": "Intelligence Diagnostic Report",
  "Geri Kazanım & Sonuç Merkezi": "Recovery & Outcome Center",
  "İşlemde": "In Progress",
  "Kapatıldı": "Closed",
  "Tamamlandı": "Completed",
  "Uçtan Uca Kurtarma Süreç Akışı": "End-to-End Recovery Process Flow",
  "TESPİT": "DETECT",
  "Sızıntıyı Yakala": "Catch Leakage",
  "SINIFLA": "CLASSIFY",
  "Kategoriyi Belirle": "Determine Category",
  "ANALİZ": "ANALYZE",
  "Nedeni İncele": "Examine Cause",
  "STRATEJİ": "STRATEGY",
  "Yöntem Belirle": "Determine Method",
  "AKSİYON": "ACTION",
  "Teması Başlat": "Initiate Contact",
  "TAKİP": "TRACK",
  "Süreci İzle": "Monitor Process",
  "KURTARMA": "RECOVERY",
  "Geliri Geri Al": "Recover Revenue",
  "Davranışsal Hatırlatıcı İstihbaratı": "Behavioral Reminder Intelligence",
  "Kartı Göster": "Show Card",
  "Unutulmuş ve askıya alınmış fırsatların toplamı.": "Total of forgotten and suspended opportunities.",
  "Kurtarılabilir Gelir Potansiyeli": "Recoverable Revenue Potential",
  "AI Geri Kazanım Kural Motoru başarı tahmini (%45).": "AI Recovery Rule Engine success estimate (45%).",
  "Döngüsü Kurtarılan Ciro": "Loop Recovered Revenue",
  "Geri kazanılmış ve loop döngüsü kapatılmış ciro.": "Recovered and loop-closed revenue.",
  "Terk Edilmiş Fırsatlar": "Abandoned Opportunities",
  "Abonelik Çürümesi": "Subscription Decay",
  "Soğuyan İlişkiler": "Cooling Relationships",
  "Döngü Otomasyon Modu": "Loop Automation Mode",
  "Aksiyon mesajlarının arka planda otomatik zamanlanmasını simüle edin.": "Simulate automatic background scheduling of action messages.",
  "Tüm Fırsatlar": "All Opportunities",
  "Bekleyenler": "Pending",
  "Takip Başlatılanlar": "Action Started",
  "Kapatılanlar": "Closed",
  "Sıralama": "Sort By",
  "Öncelik (Yüksek)": "Priority (High)",
  "Risk Tutarı (Yüksek)": "Risk Amount (High)",
  "Son İşlem Tarihi": "Last Action Date",
  "Tebrikler!": "Congratulations!",
  "Bu kategoride acil risk tespiti bulunamadı.": "No urgent risk detected in this category.",
  "Yetkili:": "Contact:",
  "Proje / Kapsam": "Project / Scope",
  "Firma Sayisi": "Company Count",
  "Hesaplanan Kacak Tutari": "Calculated Leaked Amount",
  "Tarih": "Date"
};

for (const [key, value] of Object.entries(replacements)) {
  content = content.replace(new RegExp(key.replace(/[.*+?^${}()|[\]\\]/g, '\\$&'), 'g'), value);
}

fs.writeFileSync(path, content, 'utf8');
console.log("Translation done for DiagnosisView");
